<?php
// $Id$

/**
 * @file Gives some basic examples of easy javascript functionality
 * you can add to your site to improve the user experience
 */

/**
 * Implements hook_help().
 */
function rocketsurgery_help($path, $arg){
  if ($path == 'admin/help#rocketsurgery'){
    return t('Gives some basic examples of easy javascript functionality to implement to improve the user experience.');
  }
}

/**
 * Implements hook_menu().
 *
 * @todo Make sure that permission stuff is implemented and works
 */
function rocketsurgery_menu(){
  $items = array();
  $items['admin/config/user-interface/rocketsurgery'] = array(
    'title' => 'Rocket Surgery',
    'description' => 'Administer javascript UI widgets',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rocketsurgery_adminform'),
    'access callback' => 'user_access',
    'access arguments' => array('Administer Rocket Surgery widgets'),
  );
  return $items;
}

/**
 * Implements hook_module_perm().
 */
function rocketsurgery_module_perm(){
  return array('Administer Rocket Surgery widgets');
}

/**
 * Defines the administration page form
 *
 * @todo Let users configure the CSS selectors
 */
function rocketsurgery_adminform(){
  $form = array();
  $form['rocketsurgery_floatingmenu'] = array(
    '#type' => 'fieldset',
    '#title' => 'Floating menu',
    '#description' => t("Sets the main menu position to fixed when scrolling down the page, so that it's always easily available"),
  );
  $form['rocketsurgery_floatingmenu']['rocketsurgery_floatingmenu_active'] = array(
    '#type' => 'checkbox',
    '#title' => 'Activate floating menu',
    '#default_value' => variable_get('rocketsurgery_floatingmenu_active', 'FALSE'),
    '#required' => FALSE,
 	);
  $form['rocketsurgery_floatingmenu']['rocketsurgery_floatingmenu_selector'] = array(
    '#type' => 'textfield',
    '#title' => 'JQuery selector',
    '#description' => t("Choose the CSS selector for the elements you want to target, by default (based on Bartik theme) '#main-menu' is used."),
    '#default_value' => variable_get('rocketsurgery_floatingmenu_selector', '#main-menu'),
    '#required' => TRUE,
  );

  $form['rocketsurgery_keyboardscroll'] = array(
    '#type' => 'fieldset',
    '#title' => 'Keyboard Scroll',
    '#description' => t("Lets you traverse the nodes in listings by pressing J for next, and K for previous."),
  );
  $form['rocketsurgery_keyboardscroll']['rocketsurgery_keyboardscroll_active'] = array(
    '#type' => 'checkbox',
    '#title' => 'Activate keyboard Scroll',
    '#default_value' => variable_get('rocketsurgery_keyboardscroll_active', 'FALSE'),
    '#required' => FALSE,
 	);
  $form['rocketsurgery_keyboardscroll']['rocketsurgery_keyboardscroll_selector'] = array(
    '#type' => 'textfield',
    '#title' => 'JQuery selector',
    '#description' => t("Choose the CSS selector for the elements you want to target, by default (based on Bartik theme) '#block-system-main .node' is used."),
    '#default_value' => variable_get('rocketsurgery_keyboardscroll_selector', '#block-system-main .node'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_page
 *
 * @todo Either disable for admin theme, or let user choose if to apply there too.
 * @todo drupal_add_js should target footer
 *
 * @param type $variables
 */
function rocketsurgery_preprocess_page(&$variables){
  $options = array(
      'type' => 'file',
      'scope' => 'footer',
  );

  $settings_js = array();

  if(variable_get('rocketsurgery_floatingmenu_active', 'FALSE') == TRUE){
    drupal_add_js(drupal_get_path('module', 'rocketsurgery') . '/js/floatingmenu.js', $options);
    $settings_js['rocketsurgery']['floatingmenu'] = array('selector' => variable_get('rocketsurgery_floatingmenu_selector', '#main-menu'));

  }
  if(variable_get('rocketsurgery_keyboardscroll_active', 'FALSE') == TRUE){
    drupal_add_js(drupal_get_path('module', 'rocketsurgery') . '/js/keyboardscroll.js', $options);
    $settings_js['rocketsurgery']['keyboardscroll'] = array('selector' => variable_get('rocketsurgery_keyboardscroll_selector', '#main-menu'));
  }

  // Send settings variables to javascript
  drupal_add_js($settings_js, 'setting');
}